name: sc-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python
  - scanpy
  - pandas
  - scikit-learn
  - leidenalg
  - matplotlib-base
  - r-base
  - r-seurat
  - r-optparse
  - r-stringi
  - r-dplyr
  - r-ggplot2
  - multiqc
  - celltypist
  - bioconductor-singler
  - bioconductor-celldex
