name: sc-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - scanpy
  - pandas
  - scikit-learn
  - leidenalg
  - matplotlib-base
  - r-base=4.2.0
  - r-seurat
  - r-optparse
  - r-stringi
  - r-dplyr 
  - r-ggplot2
  - icu=70.1
