name: Pipeline CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-pipeline:
    name: Run Nextflow Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "latest"

      # This installs Mamba so we can create environments
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Test Scanpy Backend
        # We now use -profile conda instead of docker
        run: nextflow run main.nf -profile conda --backend scanpy

      - name: Test Seurat Backend
        run: nextflow run main.nf -profile conda --backend seurat
