name: Pipeline CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-pipeline:
    name: Run Nextflow Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: "latest"

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: sc-pipeline
          environment-file: environment.yml
          auto-activate-base: false

      - name: Test Scanpy Backend
        shell: bash -el {0}
        run: |
          nextflow run main.nf --backend scanpy

      - name: Test Seurat Backend
        shell: bash -el {0}
        run: |
          nextflow run main.nf --backend seurat
